---
name: Practica Integradora Algoritmos
locale: es
type: practice
beta: false
teacher_info: ''
language: gobstones
id_format: "%05d"
order:
- 1
- 2
- 3
- 5
- 4
- 7
- 6
- 8
- 9
- 10
- 11
- 12
- 13
- 14
